version: "3.2"

services:
  appreport:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appreport
    ports:
      - 8900:80
    depends_on:
      - db
  db:
    image: postgres:13.5
    container_name: psqlappreport
    hostname: psqlappreport
    volumes:
      - ./pgsql:/var/lib/postgres/data
    environment:
      POSTGRES_DB:       ${POSTGRES_DB}
      POSTGRES_USER:     ${POSTGRES_USR}
      POSTGRES_PASSWORD: ${POSTGRES_PWD}
    ports:
      - "5433:5432"
    restart: always
  # imagen encargada de realizar los backups de seguridad
  pg_backup_s3:
    image: eeshugerman/postgres-backup-s3:13
    environment:
      SCHEDULE: '@every 6h00m00s'     # optional
      BACKUP_KEEP_DAYS: 1     # optional
      PASSPHRASE: ${PASSPHRASE}  # optional
      S3_REGION: ${S3_REGION}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_PREFIX: ${S3_PREFIX}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DATABASE: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USR}
      POSTGRES_PASSWORD: ${POSTGRES_PWD}
    restart: always

